'use client';

import { goalStatusStyle } from '@/lib/statusConfig';
import type { AiRoadmap, Goal, Topic } from '@/types';
import { ChevronDown, ChevronRight, Pencil, Plus, Star, Target } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useRouter } from 'next/navigation';

interface Props {
  activeGoals: Goal[];
  completedGoals: Goal[];
  finalGoal: string;
  openGoals: Record<string, boolean>;
  showCompleted: boolean;
  adoptedRoadmap: AiRoadmap | null;
  getTopics: (goalId: string) => Topic[];
  getCategories: (goalId: string) => string[];
  getPct: (goalId: string) => number;
  getCatPct: (goalId: string, cat: string) => number;
  onToggleGoal: (id: string) => void;
  onToggleTopic: (topic: Topic) => void;
  onEdit: (goal: Goal) => void;
  onAdd: () => void;
  onToggleCompleted: () => void;
}

export default function MyGoalsView({
  activeGoals,
  completedGoals,
  finalGoal,
  openGoals,
  showCompleted,
  adoptedRoadmap,
  getTopics,
  getCategories,
  getPct,
  getCatPct,
  onToggleGoal,
  onToggleTopic,
  onEdit,
  onAdd,
  onToggleCompleted,
}: Props) {
  const t = useTranslations('goals');
  const tStatus = useTranslations('status');
  const router = useRouter();

  // 로드맵 자동 생성 목표 (stage_level 있음, roadmap_id 있음) — 단계 헤더 역할
  const roadmapHeaderGoals = activeGoals.filter(
    (g) => g.stage_level !== null && g.stage_level !== undefined && g.roadmap_id !== null
  );

  // 유저가 특정 단계에 연결한 목표 (stage_level 있음, roadmap_id 있음, 자동생성 아닌 것)
  // 자동생성은 로드맵 채택 시 생성된 것 — 이름이 stage.title과 같은 것
  const getAutoGeneratedGoalForStage = (stageLevel: number) =>
    activeGoals.find((g) => g.stage_level === stageLevel && g.is_auto_generated === true);

  const getUserGoalsForStage = (stageLevel: number) => {
    return activeGoals.filter(
      (g) => g.stage_level === stageLevel && g.is_auto_generated !== true && g.roadmap_id === adoptedRoadmap?.id
    );
  };

  // 로드맵 미연결 독립 목표
  const independentGoals = activeGoals.filter((g) => g.stage_level === null || g.stage_level === undefined);

  const renderGoalCard = (g: Goal, isDone = false, isSubGoal = false) => {
    const goalTopics = getTopics(g.id);
    const categories = getCategories(g.id);
    const pct = getPct(g.id);
    const isOpen = openGoals[g.id] ?? false;

    return (
      <div
        key={g.id}
        className={`bg-surf rounded-xl border overflow-hidden ${
          g.status === 'in_progress' ? 'border-pri/40' : g.status === 'completed' ? 'border-green-200' : 'border-border'
        } ${isDone ? 'opacity-70' : ''} ${isSubGoal ? 'border-l-4 border-l-pri/40' : ''}`}
      >
        <div className="p-3">
          <div className="flex items-center gap-2">
            <div
              className={`w-3 h-3 rounded-full flex-shrink-0 ${
                g.status === 'completed' ? 'bg-green-400' : g.status === 'in_progress' ? 'bg-pri' : 'bg-border'
              }`}
            />
            <div className="flex-1 min-w-0 cursor-pointer" onClick={() => router.push(`goals/${g.id}`)}>
              <div className="flex items-center gap-1.5">
                {g.is_focus && <Star size={11} className="text-pri flex-shrink-0" fill="currentColor" />}
                <p
                  className={`text-sm font-semibold truncate ${
                    g.status === 'completed'
                      ? 'line-through text-ink-faint'
                      : g.status === 'planned'
                        ? 'text-ink-faint'
                        : 'text-ink'
                  }`}
                >
                  {g.name}
                </p>
              </div>
              {g.description && <p className="text-xs text-ink-faint mt-0.5 truncate">{g.description}</p>}
            </div>
            <div className="flex items-center gap-1.5 flex-shrink-0">
              {goalTopics.length > 0 && <span className="text-xs font-semibold text-pri">{pct}%</span>}
              <span className={`text-xs px-2 py-0.5 rounded-full ${goalStatusStyle[g.status]}`}>
                {tStatus(g.status)}
              </span>
              <button onClick={() => onEdit(g)} className="text-ink-faint hover:text-pri transition-colors">
                <Pencil size={13} />
              </button>
              {goalTopics.length > 0 && (
                <button onClick={() => onToggleGoal(g.id)} className="text-ink-faint">
                  {isOpen ? <ChevronDown size={15} /> : <ChevronRight size={15} />}
                </button>
              )}
            </div>
          </div>
          {goalTopics.length > 0 && (
            <div className="flex items-center gap-2 mt-2 ml-5">
              <div className="flex-1 h-1 bg-surf-2 rounded-full overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all ${g.status === 'completed' ? 'bg-green-400' : 'bg-pri'}`}
                  style={{ width: `${pct}%` }}
                />
              </div>
              <span className="text-xs text-ink-faint">
                {goalTopics.filter((tp) => tp.completed).length}/{goalTopics.length}
              </span>
            </div>
          )}
        </div>
        {isOpen && (
          <div className="border-t border-border px-3 py-2 flex flex-col gap-3">
            {categories.map((cat) => {
              const catTopics = goalTopics.filter((tp) => tp.category === cat);
              const catPct = getCatPct(g.id, cat);
              return (
                <div key={cat}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-medium text-ink-dim">{cat}</span>
                    <span className="text-xs text-ink-faint">{catPct}%</span>
                  </div>
                  <div className="h-1 bg-surf-2 rounded-full overflow-hidden mb-1.5">
                    <div className="h-full bg-pri-2 rounded-full" style={{ width: `${catPct}%` }} />
                  </div>
                  <div className="flex flex-col gap-1">
                    {catTopics.map((topic) => (
                      <div
                        key={topic.id}
                        className="flex items-center gap-2 cursor-pointer py-0.5"
                        onClick={() => onToggleTopic(topic)}
                      >
                        <span
                          className={`text-xs flex-shrink-0 w-4 ${topic.completed ? 'text-green-500' : 'text-pri-2'}`}
                        >
                          {topic.completed ? '✓' : '○'}
                        </span>
                        <span
                          className={`text-xs flex-1 ${topic.completed ? 'line-through text-ink-faint' : 'text-ink-dim'}`}
                        >
                          {topic.name}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    );
  };

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <p className="text-sm font-semibold text-ink">{t('finalGoalTitle', { goal: finalGoal })}</p>
        <button onClick={onAdd} className="text-pri hover:opacity-80 transition-colors">
          <Plus size={18} />
        </button>
      </div>

      {/* 로드맵 단계별 그룹 */}
      {adoptedRoadmap &&
        adoptedRoadmap.stages.map((stage) => {
          const headerGoal = getAutoGeneratedGoalForStage(stage.level);
          const subGoals = getUserGoalsForStage(stage.level);

          return (
            <div key={stage.level} className="flex flex-col gap-2">
              {/* 단계 헤더 — 자동 생성 목표 */}
              <div className="flex items-center gap-2">
                <div
                  className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0 ${
                    headerGoal?.status === 'completed'
                      ? 'bg-green-500 text-white'
                      : headerGoal?.status === 'in_progress'
                        ? 'bg-pri text-on-pri'
                        : 'bg-surf-2 text-ink-dim'
                  }`}
                >
                  {stage.level}
                </div>
                <div
                  className={`flex-1 min-w-0 ${headerGoal ? 'cursor-pointer' : ''}`}
                  onClick={() => headerGoal && router.push(`goals/${headerGoal.id}`)}
                >
                  <p className="text-xs font-semibold text-ink-dim truncate">{stage.title}</p>
                  <p className="text-xs text-ink-faint truncate">{stage.description}</p>
                </div>
                {headerGoal && getTopics(headerGoal.id).length > 0 && (
                  <span className="text-xs font-semibold text-pri flex-shrink-0">{getPct(headerGoal.id)}%</span>
                )}
                {headerGoal && (
                  <button
                    onClick={() => onEdit(headerGoal)}
                    className="text-ink-faint hover:text-pri transition-colors flex-shrink-0"
                  >
                    <Pencil size={12} />
                  </button>
                )}
              </div>

              {/* 유저가 이 단계에 연결한 하위 목표들 */}
              {subGoals.length > 0 && (
                <div className="ml-8 flex flex-col gap-2 border-l-2 border-border pl-3">
                  {subGoals.map((g) => renderGoalCard(g, false, true))}
                </div>
              )}
            </div>
          );
        })}

      {/* 독립 목표 (로드맵 미연결) */}
      {independentGoals.length > 0 && (
        <div className="flex flex-col gap-2">
          {adoptedRoadmap && (
            <p className="text-xs font-bold text-ink-faint uppercase tracking-wider mt-1">{t('otherGoals')}</p>
          )}
          {independentGoals.map((g) => renderGoalCard(g))}
        </div>
      )}

      {/* 최종 목표 카드 */}
      <div className="flex justify-start pl-4 py-0.5">
        <div className="w-px h-3 bg-border" />
      </div>
      <div className="bg-surf-2 border border-pri/30 rounded-xl p-3 flex items-center gap-3">
        <Target size={18} strokeWidth={1.8} className="text-pri flex-shrink-0" />
        <div>
          <p className="text-sm font-bold text-pri">{finalGoal}</p>
          <p className="text-xs text-ink-dim mt-0.5">{t('finalGoalSub')}</p>
        </div>
      </div>

      {/* 완료된 목표 */}
      {completedGoals.length > 0 && (
        <div className="mt-2">
          <button
            onClick={onToggleCompleted}
            className="flex items-center gap-1.5 text-xs font-bold text-ink-faint uppercase tracking-wider hover:text-ink-dim transition-colors"
          >
            {showCompleted ? <ChevronDown size={13} /> : <ChevronRight size={13} />}
            {t('completedGoals')} ({completedGoals.length})
          </button>
          {showCompleted && (
            <div className="flex flex-col gap-2 mt-2">{completedGoals.map((g) => renderGoalCard(g, true))}</div>
          )}
        </div>
      )}
    </div>
  );
}
